services:
  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Berlin
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - internal  # DB stays in the internal network

  web:
    build: .
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      INSTALL_ACTION: basic
      TZ: Europe/Berlin
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - internal  # For DB com
      - frontend  # For Traefik com
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elmo-router.rule=Host(`env.rz-vm182.gfz.de`) && PathPrefix(`/elmo`)"
      - "traefik.http.routers.elmo-router.entrypoints=https"
      - "traefik.http.routers.elmo-router.middlewares=elmo-stripprefix"
      - "traefik.http.middlewares.elmo-stripprefix.stripprefix.prefixes=/elmo"
      - "traefik.http.services.elmo-service.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"  # Traefik network

  web-msl:
    build: .
    ports:
      - "8081:80"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      INSTALL_ACTION: basic
      TZ: Europe/Berlin
      MSL_ENABLED: "true"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - internal  # For DB com
      - frontend  # For Traefik com
    volumes:
      - ./sample_settings_msl.php:/var/www/html/sample_settings.php:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elmo-msl-router.rule=Host(`env.rz-vm182.gfz.de`) && PathPrefix(`/elmo-msl`)"
      - "traefik.http.routers.elmo-msl-router.entrypoints=https"
      - "traefik.http.routers.elmo-msl-router.middlewares=elmo-msl-stripprefix"
      - "traefik.http.middlewares.elmo-msl-stripprefix.stripprefix.prefixes=/elmo-msl"
      - "traefik.http.services.elmo-msl-service.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"  # Traefik network

volumes:
  db_data:

networks:
  internal:
    driver: bridge
  frontend:
    external:
      name: traefik