services:
  db:
    image: mariadb:11
    env_file:
      - developer.env
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  web:
    build: .
    env_file:
      - developer.env
    ports:
      - "8080:80"
    environment:
      INSTALL_ACTION: basic
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      # Mount the entire project directory for live code changes.
      # This is only for development. No way to production.
      - .:/var/www/html

volumes:
  db_data: