version: '3.8'

services:
  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Berlin
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - internal

  web:
    build: .
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      INSTALL_ACTION: basic
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_AUTH: ${SMTP_AUTH}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_SENDER: ${SMTP_SENDER}
      FEEDBACK_ADDRESS: ${FEEDBACK_ADDRESS}
      XML_SUBMIT_ADDRESS: ${XML_SUBMIT_ADDRESS}
      TZ: Europe/Berlin
      # Flags for Standard ELMO
      SHOW_MSL_LABS: "false"
      SHOW_MSL_VOCABS: "false"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - internal
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elmo-router.rule=Host(`env.rz-vm182.gfz.de`) && PathPrefix(`/elmo`)"
      - "traefik.http.routers.elmo-router.entrypoints=https"
      - "traefik.http.routers.elmo-router.middlewares=elmo-stripprefix"
      - "traefik.http.middlewares.elmo-stripprefix.stripprefix.prefixes=/elmo"
      - "traefik.http.services.elmo-service.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"

  web-msl:
    build: .
    ports:
      - "8081:80"
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      # No install routine
      INSTALL_ACTION: skip
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_AUTH: ${SMTP_AUTH}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_SENDER: ${SMTP_SENDER}
      FEEDBACK_ADDRESS: ${FEEDBACK_ADDRESS}
      XML_SUBMIT_ADDRESS: ${XML_SUBMIT_ADDRESS}
      TZ: Europe/Berlin
      # Flags for msl
      SHOW_MSL_LABS: "true"
      SHOW_MSL_VOCABS: "true"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - internal
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elmo-msl-router.rule=Host(`env.rz-vm182.gfz.de`) && PathPrefix(`/elmo-msl`)"
      - "traefik.http.routers.elmo-msl-router.entrypoints=https"
      - "traefik.http.routers.elmo-msl-router.middlewares=elmo-msl-stripprefix"
      - "traefik.http.middlewares.elmo-msl-stripprefix.stripprefix.prefixes=/elmo-msl"
      - "traefik.http.services.elmo-msl-service.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"

volumes:
  db_data:

networks:
  internal:
    driver: bridge
  frontend:
    external:
      name: traefik
