version: '3.8' # compiled by google gemini flash 2.5

services:
  db:
    image: mariadb:11
    container_name: elmo-db # Optional: gives the container a predictable name
    env_file:
      - stack.env # Loads environment variables from the stack.env file
    environment: 
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Berlin
    volumes:
      - db_data:/var/lib/mysql # Persistent volume for database data
    restart: unless-stopped
    # The 'db' service does not need any Traefik labels as it's not directly exposed to the internet.
    # It communicates internally with the 'web' service via the Docker network.

  web:
    build: .
    container_name: elmo-web # Optional: gives the container a predictable name
    ports:
      - "8080:80" # Maps host port 8080 to container port 80.
                 # While Traefik handles external routing, this mapping might be
                 # required by your department's Portainer setup for monitoring,
                 # or to allow direct access to the service via VM_IP:8080 for debugging.
                 # For public access via Traefik, this specific host port mapping is redundant,
                 # but it's kept here as per your existing configuration.
    env_file:
      - stack.env # Loads environment variables from the stack.env file
    environment:
      DB_HOST: db # 'db' is the service name, Docker's internal DNS resolves this to the db container's IP
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      INSTALL_ACTION: basic
      TZ: Europe/Berlin
    depends_on:
      - db # Ensures the 'db' service starts before 'web'
    restart: unless-stopped
    volumes:
      # Mounts local directories as read-only volumes inside the container.
      # This is useful for development (instant code changes without rebuilding image)
      # or for providing dynamic content/configuration external to the image.
      # Even if the container image is immutable, these mounted files can be updated
      # independently on the host.
      - ./js:/var/www/html/js:ro
      - ./formgroups:/var/www/html/formgroups:ro
      - ./api:/var/www/html/api:ro
      - ./css:/var/www/html/css:ro
      - ./doc:/var/www/html/doc:ro
      - ./lang:/var/www/html/lang:ro
      - ./save:/var/www/html/save:ro # If this directory needs to be writable by the app, remove ':ro'
      - ./install.html:/var/www/html/install.html:ro
      - ./modals.html:/var/www/html/modals.html:ro

    # --- Traefik Labels: These labels configure Traefik to route external traffic to this 'web' service ---
    labels:
      # traefik.enable=true:
      #   This label tells Traefik to enable routing for this specific service.
      #   Without this, Traefik will ignore the other Traefik-related labels on this container.
      - "traefik.enable=true"

      # traefik.http.routers.elmo-router.rule:
      #   Defines the routing rule for this service.
      #   - Host(`env.rz-vm182.gfz.de`): Matches incoming requests where the host header is exactly 'env.rz-vm182.gfz.de'.
      #   - PathPrefix(`/elmo`): Matches incoming requests where the URL path starts with '/elmo'.
      #   The '&&' operator means both conditions must be true for the router to activate.
      - "traefik.http.routers.elmo-router.rule=Host(`env.rz-vm182.gfz.de`) && PathPrefix(`/elmo`)"

      # traefik.http.routers.elmo-router.entrypoints=https:
      #   Specifies which Traefik entrypoint(s) this router should listen on.
      #   'https' indicates that this service should be accessible via HTTPS (port 443, typically).
      #   Based on your dashboard, 'https' is the standard for your environment.
      - "traefik.http.routers.elmo-router.entrypoints=https"

      # traefik.http.routers.elmo-router.middlewares=elmo-stripprefix@docker:
      #   Attaches a middleware to this router.
      #   'elmo-stripprefix@docker' refers to the middleware defined below.
      #   This middleware will be applied to the request *before* it's sent to the service.
      - "traefik.http.routers.elmo-router.middlewares=elmo-stripprefix@docker"

      # traefik.http.middlewares.elmo-stripprefix.stripprefix.prefixes=/elmo:
      #   Defines a middleware named 'elmo-stripprefix'.
      #   'stripprefix' is a Traefik middleware type that removes a specified prefix from the request URL path.
      #   'prefixes=/elmo' means that if the incoming path is '/elmo/some/page', it will be rewritten to '/some/page'
      #   before being sent to your 'web' container. This is crucial because your web app likely expects to
      #   be served from the root path ('/'), not '/elmo/'.
      #   '@docker' is a convention indicating that this middleware is defined via the Docker provider.
      - "traefik.http.middlewares.elmo-stripprefix.stripprefix.prefixes=/elmo"

      # traefik.http.services.elmo-service.loadbalancer.server.port=80:
      #   Defines the backend service that the router will forward traffic to.
      #   'elmo-service' is the name of this internal Traefik service.
      #   'loadbalancer.server.port=80' tells Traefik that the 'web' container is listening
      #   on port 80 internally. Traefik will direct traffic to this port within the container's network.
      - "traefik.http.services.elmo-service.loadbalancer.server.port=80"
    
    # --- Network Configuration ---
    # Containers need to be on the same network as Traefik for discovery and routing.
    # They also need to be on a common network for internal communication (e.g., web to db).
    networks:
      - traefik_network # Connects 'web' to the external Traefik network
      - default         # Connects 'web' to the default internal network (for 'db' communication)

# --- Network Definitions ---
networks:
  traefik_network:
    external: true # Indicates that 'traefik_network' already exists and was created externally (e.g., by Traefik's own setup)
  default:
    # This defines the 'default' network that Docker Compose creates for services
    # within the same docker-compose.yaml file, allowing 'web' and 'db' to communicate.
    # It's good practice to explicitly define it for clarity, even if it's implicitly created.

volumes:
  db_data: # Declares a named volume for persistent database storage. Docker manages its location.