name: PHP 8.4 Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: mde2-msl-test
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_mysql, mysqli, zip
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install JS dependencies
      run: |
        npm install

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest
        composer dump-autoload -o

    - name: Wait for MySQL to be ready
      run: |
        for i in {30..0}; do
          if mysqladmin ping -h127.0.0.1 --silent; then
            break
          fi
          echo 'Waiting for MySQL...'
          sleep 5
        done
        if [ "$i" = 0 ]; then
          echo >&2 'MySQL did not start in time.'
          exit 1
        fi

    - name: Grant privileges to test_user
      run: |
        mysql -h127.0.0.1 -uroot -proot_password -e "
          CREATE USER IF NOT EXISTS 'test_user'@'%' IDENTIFIED BY 'test_password';
          GRANT ALL PRIVILEGES ON *.* TO 'test_user'@'%';
          FLUSH PRIVILEGES;
        "

    - name: Create settings.php
      run: |
        cat << EOF > settings.php
        <?php
        function connectDb() {
            \$host = '127.0.0.1';
            \$username = 'test_user';
            \$password = 'test_password';
            \$database = 'mde2-msl-test';
            \$conn = new mysqli(\$host, \$username, \$password, \$database);
            return \$conn;
        }

        function getApiKey() {
            \$apiKeyGoogleMaps = 'test_api_key';
            echo json_encode(['apiKey' => \$apiKeyGoogleMaps]);
        }

        if (basename(__FILE__) == basename(\$_SERVER['PHP_SELF'])) {
            if (\$_SERVER['REQUEST_METHOD'] === 'GET') {
                getApiKey();
            }
        }

        \$connection = connectDb();

        \$apiKeyElmo = '1234-1234-1234-1234';

        \$apiKeyTimezone = 'test_timezone_api_key';
        \$maxTitles = 2;
        \$mslLabsUrl = 'https://raw.githubusercontent.com/UtrechtUniversity/msl_vocabularies/main/vocabularies/labs/labnames.json';

        \$showFeedbackLink = true;
        \$smtpHost = 'smtp.test.de';
        \$smtpPort = 465;
        \$smtpUser = 'test_user';
        \$smtpPassword = 'test_password';
        \$smtpSender = 'test_sender@test.com';
        \$feedbackAddress = 'feedback@test.com';
        EOF

    - name: Initialize database structure and lookup data
      run: php -r "require 'install.php'; createDatabaseStructure(\$connection); insertLookupData(\$connection);"

    - name: Start PHP built-in web server
      run: |
        php -S localhost:8000 -t . tests/server.php 2>&1 > server.log &
        echo $! > server.pid
        sleep 10
        
        echo "Testing initial API endpoints:"
        curl -v http://localhost:8000/api/v2/general/alive
        echo "\nTesting licenses endpoint:"
        curl -v http://localhost:8000/api/v2/vocabs/licenses/all
        
        echo "\nInitial server log contents:"
        cat server.log
        echo "\nPHP error log:"
        if [ -f /var/log/php_errors.log ]; then
          cat /var/log/php_errors.log
        fi

    - name: Set PHPUnit permissions
      run: chmod +x vendor/bin/phpunit

    - name: Run PHPUnit tests
      env:
        API_BASE_URL: http://localhost:8000
      run: |
        vendor/bin/phpunit --configuration phpunit.xml --coverage-clover coverage.xml --debug
        
        echo "\nFinal Server Log:"
        cat server.log

    - name: Stop PHP server
      if: always()
      run: kill $(cat server.pid)